### ISSUE TITLE
consider SIGABRT

### ISSUE THREAD

**Issue by bAndie91** [Theldus/safemalloc#1]
hi, sorry barking into it, i just want to draw your attention on SIGABRT. i have seen memory management libs like this calling `abort()` on `malloc()` failures. maybe worth to evaluate if it's beneficial if you have not done it yet.
IMO it's good to signal this kind of low level failure by a signal, not just a nonzero exit code, which may be a legitime exit code of the program indicating some status (like `test` from coreutils).

https://github.com/Theldus/safemalloc/blob/b9470040b701132a36eb008176d5beaf5ba04420/sfmalloc.h#L134

btw I like this lib, its idea and implementation.

**Comment by Theldus** [comment]
Hi @bAndie91,
(I'm sorry for the huge delay, for some reason I wasn't 'watching' this repo, so I wasn't notified of the issue)

It makes a lot of sense, actually. Furthermore, the `ON_ERROR_ABORT` flag implies that the program aborts, rather than simply returning an error code.

However, invoking `abort()` causes the cleanup routines registered in `atexit()` not to be invoked. Perhaps a better approach would be:
a) abort execution on `ON_ERROR_ABORT`.
b) add a new flag, let's say `ON_ERROR_EXIT` that would terminate the process with an error code. 

This error code can even be configurable by another macro as a way to allow the user to select a code not used by the rest of the program.
